# This is for https://travis-ci.org/ - you can ignore it.
language: java


jobs:
  include:
    - arch: amd64
      dist: xenial
    - arch: amd64
      dist: bionic
    - arch: ppc64le
      dist: xenial
    - arch: ppc64le
      dist: bionic
      
before_script: 
  - echo $JAVA_HOME
  - ls -l /lib/jvm
  - mvn --version && which mvn && echo $PATH
