# This is for https://travis-ci.org/ - you can ignore it.
language: java
jdk:
  - openjdk8

jobs:
  include:
    - arch: amd64
      dist: xenial
    - arch: amd64
      dist: bionic
    - arch: ppc64le
      dist: xenial
    - arch: ppc64le
      dist: bionic
      
before_script: mvn --version && which mvn && echo $PATH
